version: '3.8'

services:
  event-logger:
    build: ./event-logger
    ports:
      - "3500:3500"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run dev
    networks:
      - app_network

  chat:
    build: ./chat
    ports:
      - "5173:5173"
    depends_on:
      - event-logger
    command: npm run dev
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
